"""Portfolio-safe temporal contextualization utilities for GeoValora AI.

The private application reads documented external factors from project assets.
This public version receives those factors as data, avoiding redistribution of
private project artifacts while preserving the core validation logic.

Important: contextualization is not a new XGBoost prediction.
"""

from __future__ import annotations

import math
from typing import Any, Mapping


_REQUIRED_SCENARIOS = ("conservative", "central", "upper")


def validate_city_context(context: Mapping[str, Any]) -> dict[str, float]:
    """Validate and normalize a city's three contextualization factors."""
    if not isinstance(context, Mapping):
        raise TypeError("context must be a mapping.")

    factors: dict[str, float] = {}

    for scenario in _REQUIRED_SCENARIOS:
        if scenario not in context:
            raise KeyError(f"Missing temporal factor: {scenario}")

        factor = float(context[scenario])
        if not math.isfinite(factor) or factor <= 0:
            raise ValueError(f"Invalid temporal factor for {scenario}.")

        factors[scenario] = factor

    if not (
        factors["conservative"]
        <= factors["central"]
        <= factors["upper"]
    ):
        raise ValueError(
            "Expected conservative <= central <= upper temporal factors."
        )

    return factors


def contextualize_2026(
    *,
    city: str,
    historical_prediction: float,
    factor_table: Mapping[str, Mapping[str, Any]],
    historical_lower: float | None = None,
    historical_upper: float | None = None,
    already_contextualized: bool = False,
) -> dict[str, Any]:
    """Apply externally documented scenario factors to a historical estimate.

    This is a contextual layer around the historical model output, not a new
    prediction generated by the trained model.
    """
    if already_contextualized:
        raise ValueError("Temporal contextualization cannot be applied twice.")

    prediction = float(historical_prediction)
    if not math.isfinite(prediction) or prediction <= 0:
        raise ValueError("Historical prediction must be positive and finite.")

    if (historical_lower is None) != (historical_upper is None):
        raise ValueError("Both historical interval limits must be provided.")

    if historical_lower is not None:
        historical_lower = float(historical_lower)
        historical_upper = float(historical_upper)

        if historical_lower <= 0 or historical_upper <= historical_lower:
            raise ValueError("Historical interval is invalid.")

    if city not in factor_table:
        raise ValueError(f"No temporal context is available for {city}.")

    city_payload = factor_table[city]
    factors = validate_city_context(city_payload)

    scenarios: dict[str, Any] = {}

    for scenario, factor in factors.items():
        scenario_result: dict[str, Any] = {
            "factor": factor,
            "contextual_value_2026": prediction * factor,
        }

        if historical_lower is not None:
            scenario_result["contextual_band_2026"] = {
                "lower": historical_lower * factor,
                "upper": historical_upper * factor,
            }

        scenarios[scenario] = scenario_result

    return {
        "city": city,
        "historical_value": prediction,
        "result_type": "EXTERNAL_CONTEXTUALIZATION",
        "is_direct_2026_model_prediction": False,
        "evidence": city_payload.get("evidence"),
        "scenarios": scenarios,
        "warning": (
            "2026 values are an external contextualization of the historical "
            "estimate. They are not a new model prediction, an official "
            "appraisal, or a 2026 conformal interval."
        ),
    }
